add scc
monkukui/ac-library-go pull request #21
Opened 2020-09-16 00:20 UTC by aruaru0

sccのコードのPull Requesをしました。
他の人のリポジトリへのリクエストはあまり行ったことがないのでミスがあるかもしれません。その場合はご指摘ください。

2020-09-16 00:30 UTC, nu50218 commented
テストを追加して欲しいです。
#19 と[ac-library-rs/src/scc.rs#L26](https://github.com/rust-lang-ja/ac-library-rs/blob/5103743e242264c473f1691e3380e25556198d4e/src/scc.rs#L26)が参考になると思います。

2020-09-16 04:11 UTC, aruaru0 commented
テスト追加しました。

2020-09-16 05:00 UTC, nu50218 requested changes
ありがとうございます！レビューしました。
internalの部分は移動してから見ようと思います。

2020-09-16 05:00 UTC, nu50218 commented on scc/scc.go
> +type sccPair struct {
本家のinternal::sccは、READMEにあるようにinternal/sccパッケージに作って欲しいです。

2020-09-16 05:00 UTC, nu50218 commented on scc/scc_test.go
> +	for i, s := range scc {
多分`reflect.DeepEqual`で比較できます。

2020-09-16 05:00 UTC, nu50218 commented on scc/scc.go
> +func SccGraph(n int) *SccGRAPH {
パッケージ名でscc関係であることはわかっているので、`NewGraph`とかのほうがいいような気もします。
そうすると`SccGRAPH`も`SccGraph`にできますし。

2020-09-16 05:38 UTC, aruaru0 commented on scc/scc.go
> +type sccPair struct {
これ、悩んだのですが、利用時にはソースファイルにコピペすると考えると、１つのアルゴリズムは１ファイルにまとめたほうが良いと思ったんのですがどうでしょうか。

2020-09-16 05:47 UTC, nu50218 commented on scc/scc.go
> +type sccPair struct {
それは確かにそうです…

が、一応importとかを見てシングルファイルにまとめてくれるツールがあります。

- https://github.com/monkukui/gpcg

- https://github.com/mpppk/gollup

また、需要があれば別にシングルファイルでまとめて公開すればいいかなと思うので、internal/sccにお願いしたいです。

2020-09-16 06:33 UTC, aruaru0 commented on scc/scc_test.go
> +	for i, s := range scc {
修正しました。

2020-09-16 06:38 UTC, aruaru0 commented on scc/scc.go
> +type sccPair struct {
了解です。

ただ、internal/sccに分離するとローカル環境でパッケージのbuildがうまくできないです。
(internal/scc側が参照できない）

folkした環境でのやり方ってわかりますでしょうか。
# やっていただいたほうが早いかもしれません。

2020-09-16 06:40 UTC, nu50218 commented on scc/scc.go
> +type sccPair struct {
ありがとうございます。
internalですが、もしGOPATHの下で作業されているなら、それ以外のところで作業すると動くと思います。
そうでないならわからないです…🙇‍♂️

2020-09-16 06:56 UTC, aruaru0 commented on scc/scc.go
> +type sccPair struct {
package名をinternalにすると動きました。一応分離しましたが、Go言語なので、関数名が一部大文字になっています。ご確認ください。

2020-09-16 06:57 UTC, aruaru0 commented on scc/scc.go
> +func SccGraph(n int) *SccGRAPH {
分離に合わせて修正しました。

2020-09-16 07:09 UTC, nu50218 commented on scc/scc.go
> +func SccGraph(n int) *SccGRAPH {
sampleがそのままになっていてCIが落ちているようです。修正をお願いします。

2020-09-16 07:19 UTC, aruaru0 commented on scc/scc.go
> +func SccGraph(n int) *SccGRAPH {
失礼しました。修正しました。

2020-09-16 07:59 UTC, nu50218 commented on internal/scc/scc.go
> +func (s *SccGraph) numVertics() int {
本家でpublicなのでexportしてほしいです。

2020-09-16 07:59 UTC, nu50218 commented on internal/scc/scc.go
> +package internal
```suggestion
package scc
```
sccで動くと思います。

2020-09-16 07:59 UTC, nu50218 commented on internal/scc/scc.go
> +type sccPair struct {
sccPair、sccPair2という名前だと何に使われているのか、どういう構造体なのかわかりづらいのでわかりやすい名前に変えてほしいです。

2020-09-16 07:59 UTC, nu50218 commented on internal/scc/scc.go
> +func initCsr(n int, edges []sccPair) *csr {
効率のために`[]*sccPair`で受け取って欲しいです。

2020-09-16 07:59 UTC, nu50218 commented on internal/scc/scc.go
> +func (s *SccGraph) sccIds() sccPair2 {
これは本家でpublicなのでexportしてほしいです。

2020-09-16 07:59 UTC, nu50218 commented on internal/scc/scc.go
> +type csr struct {
csrがinternal/scc内限定の用途となっていますが、他のライブラリから使われていたりはしないですか？
もし使われていて、exportするならばelistは[]intより[]interface{}のほうがいいかもしれないです。

2020-09-16 07:59 UTC, nu50218 commented on scc/sample/main.go
> +func getString() string {
使われていないです

2020-09-16 07:59 UTC, nu50218 commented on scc/sample/main.go
> +func main() {
何の問題を解くようなプログラムなのかコメントがあるとより良いと思います。

2020-09-16 07:59 UTC, nu50218 commented on internal/scc/scc.go
> +package internal
それにともなってNewSccGraphもNewGraphでお願いします。

2020-09-16 08:24 UTC, aruaru0 commented on internal/scc/scc.go
> +type csr struct {
使われていないので、[]intのままにしておきます。
本家もinternal_scc.cppなので問題ないかと思います。
他は修正しました。

2020-09-16 08:26 UTC, aruaru0 commented on internal/scc/scc.go
> +func initCsr(n int, edges []sccPair) *csr {
*[]sccPair のtypoでしょうか。
上記に変更しました。

2020-09-16 08:46 UTC, aruaru0 commented on internal/scc/scc.go
> +func (s *SccGraph) sccIds() sccPair2 {
修正しましたが、本家のドキュメントにはＡＰＩとして記載されていないのでプライベートでよいかもしれません。

2020-09-16 08:50 UTC, nu50218 commented on internal/scc/scc.go
> +func initCsr(n int, edges []sccPair) *csr {
あ、[]*sccPairです。

2020-09-16 10:32 UTC, aruaru0 commented on internal/scc/scc.go
> +func initCsr(n int, edges []sccPair) *csr {
変更しました。
go言語って、ポインタ関連勝手にreferenceとvalueが最適化される気がしていたのですが、この変更でそんなに変わるものでしょうか。

2020-09-16 13:13 UTC, nu50218 commented on internal/scc/scc.go
> +func (s *SccGraph) sccIds() sccPair2 {
sccからinternal/sccを呼ぶときに公開されていてほしいです

2020-09-16 13:17 UTC, nu50218 commented on internal/scc/scc.go
> +func initCsr(n int, edges []sccPair) *csr {
うーん、スライスなのでコピーコストはほぼかからないんですが、構造体はサイズが大きくなるにつれてコピーコストが高くなるので基本的にポインタで扱いたいです。

2020-09-17 07:24 UTC, monkukui commented on scc/scc_test.go
> +	if len(scc) != 1 {
テストが落ちると、関数名である `TestSimple` が報告されるので、このエラーメッセージは冗長かと思いました。
何も書かないか、`expected` と `actual` を報告するのがいいかと思いました！

2020-09-17 07:24 UTC, monkukui commented on scc/scc_test.go
> +	if len(scc) != 1 {
`assert.Equal` とかを使ってもいいかもしれないです！

2020-09-17 07:24 UTC, monkukui commented on scc/scc_test.go
> +		t.Fatal("failed Self Loop")
ここも同様です！

2020-09-17 07:26 UTC, monkukui commented on scc/scc_test.go
> +		t.Fatal("failed Simple")
テストが落ちると、関数名である `TestSimple` が報告されるので、このエラーメッセージは冗長かと思いました。
何も書かないか、`expected` と `actual` を報告するのがいいかと思いました！

2020-09-17 07:26 UTC, monkukui commented on scc/scc_test.go
> +		t.Fatal("failed Simple")
`assert.Equal` とかを使ってもいいかもしれないです！

2020-09-17 12:18 UTC, aruaru0 commented on scc/scc_test.go
> +		t.Fatal("failed Simple")
assert.Equalは標準ではないので使いませんでした。

2020-09-18 13:25 UTC, aruaru0 commented on scc/scc_test.go
> +		t.Fatal("failed Simple")
assert.Equalは使っていませんが`expected` `actual` を返すように変更しています。

2020-09-18 14:05 UTC, monkukui approved these changes

2020-09-18 14:05 UTC, monkukui commented on internal/scc/scc.go
> +func (s *SccGraph) numVertics() int {
export して、`scc.go` の `AddEdge(from, to)` を呼び出した時に、`from` と `to` が頂点数 `n` を超えてないかをチェックする時に使用して欲しいです。
本家の`atcoder/scc` では、

```C++
int n = internal.num_vertices();
assert(0 <= from && from < n);
assert(0 <= to && to < n);
```

のようにアサーションがあります。

2020-09-18 14:05 UTC, monkukui commented on internal/scc/scc.go
> +	dfs = func(v int) {
```Go
dfs := func(v int) {
//
}
```
でもいいかも？

2020-09-18 14:10 UTC, monkukui commented
コード全部見ました！
細かいを何点かコメントしました！
良さそうです！

2020-09-19 01:51 UTC, aruaru0 commented on internal/scc/scc.go
> +	dfs = func(v int) {
えっと、内部で再帰的に呼びだされる関数の場合は、別途宣言しないとダメ見たいです。
コンパイルエラーになります。試行錯誤してこの形になりました。

```go
dfs := func(v int) {
//
}
```

`assert`の件ですが、goだと領域外アクセスでエラーがちゃんと出力されるのでいらないかなと思って入れませんでした。Ｃ++でもデバッグモード以外ではassert入らないですし、atcoderでは`-O`付きでコンパイルされるので。

ところで、assertみたいに、テストのときだけアラート入れる仕組みってgoにありますっけ？ 教えてもらえれば、入れときます。

2020-09-19 02:56 UTC, monkukui commented on internal/scc/scc.go
> +	dfs = func(v int) {
>えっと、内部で再帰的に呼びだされる関数の場合は、別途宣言しないとダメ見たいです。
コンパイルエラーになります。試行錯誤してこの形になりました。

すいません、ではこのままでお願いします！

>ところで、assertみたいに、テストのときだけアラート入れる仕組みってgoにありますっけ？ 教えてもらえれば、入れときます。

わからないので、一旦このままで大丈夫です！

2020-09-19 03:16 UTC, monkukui commented on internal/scc/scc.go
> +func (s *SccGraph) numVertics() int {
https://github.com/monkukui/ac-library-go/pull/21#discussion_r491254429

アサーションで使わないのであれば、`numVertics()` は消してしまっていいかと思います！
本家では、`scc.cpp` でのアサーションのみで使用されているはずで、コンテスト中に `numVertics()` を呼びたくなる場面はないはずです（頂点数はコンストラクタ呼び出し時に決定するし、頂点数の追加や削除はできないため）（そもそも、本家ドキュメントに `numVertics()` について記載されていないので、内部での使用用途に限定されている）。

2020-09-19 23:49 UTC, aruaru0 commented on internal/scc/scc.go
> +func (s *SccGraph) numVertics() int {
`numVertics()`削除しました。

2020-09-20 00:01 UTC, nu50218 approved these changes

2020-09-20 05:39 UTC, monkukui commented
@aruaru0 ありがとうございました！
マージしてください！

2020-09-20 08:01 UTC, nu50218 commented
(マージ権限なさそう…？)

2020-09-20 08:01 UTC, merged